# Where things are
collections:
  words:
    output          : true
    permalink       : /:title
    # sort_by         : date_created
  snippets:
    output          : true
    permalink       : /snippets/:slug

defaults:
  - scope:
      path: ""
      type: "words"
    values:
      layout: "post"
      author: "w0lfram1te"
  - scope:
      path: ""
      type: "snippets"
    values:
      layout: "post"
      author: "w0lfram1te"

# Handling Reading
exclude             : [
  "README.md", 
  "node_modules/", 
  "Gemfile", 
  "Gemfile.lock", 
  ".git",
  ".obsidian",
  "archives",
  "package-lock.json",
  "tailwind.config.js"
]
include             : [
  "_pages",
  "_media"
]

# Serving
port                : 4000
host                : 127.0.0.1

plugins: 
  - jekyll-gist