services:
  web:
    container_name: jekyll
    image: jekyll/jekyll
    command: jekyll serve
    # command: bundle update  # use this command to update Gemfile.lock
    ports:
      - 4000:4000
    volumes: 
      - ${PWD}:/srv/jekyll:rw

# https://github.com/envygeeks/jekyll-docker/blob/master/README.md